"print('Hola mundo somos Alberto y marcos')" 
"print('Proyecto finalizado')" 
"print("Este es el cambio de Alberto")"
"print('Este es el cambio de Alberto y marcos)" 
"('Bienvenidos a nuestro proyecto')" 
